### ISSUE TITLE
checkout couldn't complete 

### ISSUE THREAD

**Issue by baseloo** [krokedil/paysoncheckout-for-woocommerce#65]
couldn't complete checkout process after viewing cart , got these error messages:

2019-04-10T10:48:27+00:00 CRITICAL Uncaught Error: Call to a member function get_name() on null in \krokedil-paysoncheckout-20-for-woocommerce\classes\requests\helpers\class-paysoncheckout-for-woocommerce-helper-cart.php:81
Stack trace:
#0 \krokedil-paysoncheckout-20-for-woocommerce\classes\requests\helpers\class-paysoncheckout-for-woocommerce-helper-cart.php(133): PaysonCheckout_For_WooCommerce_Helper_Cart->get_product_name(NULL)
#1 \krokedil-paysoncheckout-20-for-woocommerce\classes\requests\helpers\class-paysoncheckout-for-woocommerce-helper-cart.php(37): PaysonCheckout_For_WooCommerce_Helper_Cart->get_fee(Object(stdClass))
#2 \krokedil-paysoncheckout-20-for-woocommerce\classes\requests\class-paysoncheckout-for-woocommerce-create-order.php(49): PaysonCheckout_For_WooCommerce_Helper_Cart->get_cart_items()
#3 \krokedil-paysoncheckout-20-for-woocommerce\cla i \krokedil-paysoncheckout-20-for-woocommerce\classes\requests\helpers\class-paysoncheckout-for-woocommerce-helper-cart.php på rad 81

-----------------------------------------------------------------------------
and these error from debug file:
[10-Apr-2019 11:00:07 UTC] id was called incorrectly. Product properties should not be accessed directly. Backtrace: require_once('\wp-load.php'), require_once('\wp-config.php'), require_once('\wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Wad_Public->init_globals, WC_Cart->calculate_totals, WC_Cart->is_empty, WC_Cart->get_cart, WC_Cart_Session->get_cart_from_session, WC_Product_Variation->is_purchasable, WC_Product->is_purchasable, apply_filters('woocommerce_is_purchasable'), WP_Hook->apply_filters, wpas_woocommerce_is_purchasable, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.
[10-Apr-2019 11:00:07 UTC] id was called incorrectly. Product properties should not be accessed directly. Backtrace: require_once('\wp-load.php'), require_once('\wp-config.php'), require_once('\wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Cart_Session->get_cart_from_session, WC_Product_Variation->is_purchasable, WC_Product->is_purchasable, apply_filters('woocommerce_is_purchasable'), WP_Hook->apply_filters, wpas_woocommerce_is_purchasable, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.

**Comment by baseloo** [comment]
it's related with custom fee

**Comment by baseloo** [comment]
also there is one more error , auto register customer doesn't work , after this version
neither  you are using setting in woocommerce or Auto register plugin

**Comment by baseloo** [comment]
FASTCGI_RESPONSE_ERRORData2The WC_Order::add_tax function is deprecated since version 3.0. Replace with a new WC_Order_Item_Tax object and add to order with WC_Order::add_item(). ErrorCodeAccess is denied. | FASTCGI_RESPONSE_ERROR | Data2 | The WC_Order::add_tax function is deprecated since version 3.0. Replace with a new WC_Order_Item_Tax object and add to order with WC_Order::add_item(). | ErrorCode | Access is denied.
-- | -- | -- | -- | -- | --
FASTCGI_RESPONSE_ERROR
The WC_Order::add_tax function is deprecated since version 3.0. Replace with a new WC_Order_Item_Tax object and add to order with WC_Order::add_item().
Access is denied.

**Comment by MichaelBengtsson** [comment]
Hi @baseloo Sorry for a late reply on the issue.

The original issue has been resolved with the fee. However the auto register customers is working for me. Have you settup WooCommerce to automaticaly create passwords and usernames?

**Comment by MichaelBengtsson** [comment]
Closed for now, please reopen if this issue still exists for you.
